// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: email.proto

package server

import (
	"context"

	"go-storage/app/email/cmd/rpc/internal/logic"
	"go-storage/app/email/cmd/rpc/internal/svc"
	"go-storage/app/email/cmd/rpc/pb"
)

type EmailServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedEmailServer
}

func NewEmailServer(svcCtx *svc.ServiceContext) *EmailServer {
	return &EmailServer{
		svcCtx: svcCtx,
	}
}

func (s *EmailServer) Send(ctx context.Context, in *pb.SendReq) (*pb.SendResp, error) {
	l := logic.NewSendLogic(ctx, s.svcCtx)
	return l.Send(in)
}
