// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type CompleteUploadReq struct {
	FileHash string `json:"file_hash"`
}

type CompleteUploadResp struct {
}

type DownloadRangeReq struct {
	FileId uint64 `path:"file_id"`
}

type DownloadRangeResp struct {
}

type FileMeta struct {
	Id     uint64 `json:"id"`
	Hash   string `json:"hash"`
	Size   int64  `json:"size"`
	Path   string `json:"path"`
	Status int    `json:"status"`
}

type FileUesrRelation struct {
	Id            uint64 `json:"id"`
	UserId        uint64 `json:"user_id"`
	FileId        uint64 `json:"file_id"`
	FilenameAlias string `json:"filename_alias"`
	Status        int    `json:"status"`
}

type InitFileMetaReq struct {
	Hash          string `json:"hash"`
	FileSize      uint64 `json:"file_size"`
	ChunkSize     uint64 `json:"chunk_size"`
	FilenameAlias string `json:"filename_alias"`
}

type InitFileMetaResp struct {
	Hash       string `json:"hash"`
	ChunkSize  uint64 `json:"chunk_size"`
	ChunkCount int    `json:"chunk_count"`
}

type QuickTransmissionReq struct {
	Hash          string `json:"hash"`
	FilenameAlias string `json:"filename_alias"`
}

type QuickTransmissionResp struct {
}

type UploadChunkReq struct {
	FileHash   string `form:"file_hash"`
	ChunkIndex int    `form:"chunk_index"`
	ChunkSize  uint64 `form:"chunk_size"`
	ChunkHash  string `form:"chunk_hash"`
}

type UploadChunkResp struct {
}
