// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: email.proto

package email

import (
	"context"

	"go-storage/app/email/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SendReq  = pb.SendReq
	SendResp = pb.SendResp

	Email interface {
		Send(ctx context.Context, in *SendReq, opts ...grpc.CallOption) (*SendResp, error)
	}

	defaultEmail struct {
		cli zrpc.Client
	}
)

func NewEmail(cli zrpc.Client) Email {
	return &defaultEmail{
		cli: cli,
	}
}

func (m *defaultEmail) Send(ctx context.Context, in *SendReq, opts ...grpc.CallOption) (*SendResp, error) {
	client := pb.NewEmailClient(m.cli.Conn())
	return client.Send(ctx, in, opts...)
}
