// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type ActivateReq struct {
	VerifyToken string `form:"token"`
}

type ActivateResp struct {
}

type GetUserInfoReq struct {
	UserId int64 `json:"user_id"`
}

type GetUserInfoResp struct {
	UserInfo User `json:"user_info"`
}

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResp struct {
	UserId       int64  `json:"user_id"`
	Token        string `json:"token"`
	ExpireAfter  int64  `json:expire_after`
	RefreshAfter int64  `json:refresh_after`
}

type RegisterReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RegisterResp struct {
}

type ResendActivateEmailReq struct {
	Email string `json:"email"`
}

type ResendActivateEmailResp struct {
}

type User struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Avatar   string `json:"avatar"`
}
