SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `file_meta`;
CREATE TABLE `file_meta` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT,
  `hash` CHAR(64) NOT NULL DEFAULT '' COMMENT '文件唯一Hash',
  `size` BIGINT NOT NULL DEFAULT 0 COMMENT '文件大小（字节）',
  `path` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '存储路径',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '1=可用，0=删除',
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY (`hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `user_file_rel` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `file_id` BIGINT UNSIGNED NOT NULL,
  `filename_alias` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '用户命名的文件名',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY (`user_id`, `file_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;